version: '3'

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ./radarr:/config
      - ${HOME}/home-server/movies:/movies
      - ${HOME}/home-server/downloading:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media_network

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./sonarr:/config
      - ${HOME}/home-server/tvshows:/tvshows
      - ${HOME}/home-server/downloading:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media_network

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8088:80
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./qbittorrent:/config
      - ${HOME}/home-server/downloading:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media_network

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ./jackett:/config
      - ${HOME}/home-server/downloading:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media_network
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - 8191:8191
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media_network
networks:
  media_network: