version: '3'

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    # ports:
    #   - 7878:7878
    volumes:
      - ./radarr:/config
      - /mnt/1tb/movies:/mnt/media
      - /mnt/1tb/downloading:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    # ports:
    #   - 8989:8989
    #   # - 9898:9898
    volumes:
      - ./sonarr:/config
      - /mnt/1tb/tvshows:/mnt/media
      - /mnt/1tb/downloading:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
    # networks:
    #   - media_network
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    #   - 8081:80
    #   - 6881:6881
    #   - 6881:6881/udp
    volumes:
      - ./qbittorrent:/config
      - /mnt/1tb/downloading:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./readarr/config:/config
      - ./book:/books #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./bazarr/config:/config
      # - /path/to/movies:/movies #optional
      # - /path/to/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ./jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
    # networks:
    #   - media_network
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    # ports:
    #   - 8191:8191
    environment:
      - PUID=1000
      - PGID=1000
    # networks:
    #   - media_network
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/radarr-001-001.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
      - ./nginx/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
    ports:
      # - 80:80  # HTTP port
      - 443:443  # HTTPS port (if you're using SSL)