version: '3'

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    # ports:
    #   - 7878:7878
    volumes:
      - ./radarr:/config
      - /mnt/1tb/movies:/mnt/media
      - /mnt/1tb/downloading:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
    # networks:
    #   - media_network

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
    volumes:
      - ./nginx/radarr-004.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - /path/to/ssl:/etc/nginx/ssl:ro  # Optional: If you want to use SSL
    ports:
      # - 80:80  # HTTP port
      - 443:443  # HTTPS port (if you're using SSL)
